# Generated by Django 5.1.5 on 2025-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profile_pictures/perfil.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
