# Generated by Django 5.1.5 on 2025-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_productimage_products_delete_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('li', 'libra')], default='unidad', max_length=10),
        ),
    ]
